version: '3.8'

services:
  nuxt-app:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${PROJECT}.tls=true
      - traefik.http.routers.${PROJECT}.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false
