# Build Stage 1

FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

# Copy package.json and your lockfile, here we add pnpm-lock.yaml for illustration
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project
COPY . ./

# Build the project
RUN npm run build

