#default nginx configuration

server {
    listen 80;
    listen [::]:80;
    listen [::]:443;

    #server_name smallfishbusiness.on.ihumbak.website;

    location / {
        proxy_pass http://nuxt-app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Conditional Basic Auth
        set $auth_file /etc/nginx/htpasswd/.htpasswd;
        if (-f $auth_file) {
            auth_basic "Restricted Content";
            auth_basic_user_file $auth_file;
        }
    }

    # Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_min_length 1000;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_vary on;
}
